#!/bin/bash
#
## Copyright 2016 Peerchemist <peerchemist@protonmail.ch>
#
VERSION=0.3

PAM="/etc/pam.d/sshd"
SSHD="/etc/ssh/sshd_config"

function configure_pam {
	sed -i '/# \/etc\/security\/pam_env.conf./a auth    required    pam_google_authenticator.so' $PAM
}

function deconfigure_pam {
	sed -i '/auth    required    pam_google_authenticator.so/d' $PAM
}

function configure_sshd {
	sed -i "s/ChallengeResponseAuthentication no/ChallengeResponseAuthentication yes/g" $SSHD
	systemctl reload sshd
}

function deconfigure_sshd {
	sed -i "s/ChallengeResponseAuthentication yes/ChallengeResponseAuthentication no/g" $SSHD
	systemctl reload sshd
}

function status {
	if grep -Fxq "auth    required    pam_google_authenticator.so" $PAM && grep -Fxq "ChallengeResponseAuthentication yes" $SSHD;
	then
		echo True
	else
		echo False
	fi
}

#if [[ $1 == "status" ]]; then
#	status
#fi

if [[ $1 == "set" ]] && status == "False"; then
	configure_pam
	configure_sshd
	systemctl reload sshd
	echo "Enabled google-authenticator for SSH access." | systemd-cat -t pcf-set_gauth -p alert
fi

if [[ $1 == "unset" ]] && status == "True"; then
	deconfigure_pam
	deconfigure_sshd
	systemctl reload sshd
	echo "Disabled google-authenticator for SSH access." | systemd-cat -t pcf-set_gauth -p alert
fi